import { tags } from "typia";

/**
 * Attendance_parent 엔터티(학부모/보호자)의 메인 스키마입니다.
 *
 * - Prisma 모델의 모든 컬럼(id, auth_account_id, name, email, phone, created_at,
 *   updated_at)을 포함하며,
 * - Atomic(비집계, 비연산) 필드만 존재(학부모의 출결, 자녀매핑 등 외래 데이터는 참조로만 연결).
 * - 개인정보 보호 및 감사 정책상 모든 접근 이력에 활용됩니다.
 * - 본 엔티티는 학부모 서비스의 기본 회원 엔티티로 사용됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IAttendanceParent = {
  /**
   * 학부모의 고유 식별자입니다.
   *
   * Prisma attendance_parent 테이블의 id 컬럼으로, 모든 자식, 알림 채널, 접근 로그 등 다양한 참조에서
   * 사용되는 PK입니다. 이 필드는 시스템 전반에서 보호자 관련 조회, 연동, 감사 이벤트 추적 등에 참조되며, UUID 형식을
   * 강제합니다.
   */
  id: string & tags.Format<"uuid">;

  /**
   * 인증 계정(auth_account) FK입니다. 이 값은 소셜/로컬 로그인 연결 및 보호자의 로그인 인증 식별자 매핑에 사용됩니다.
   *
   * Prisma attendance_parent.auth_account_id는 반드시 attendance_auth_account와
   * 1:1대응되는 값을 가지며, 유니크 제약이 있습니다.
   */
  auth_account_id: string & tags.Format<"uuid">;

  /**
   * 학부모 이름입니다. 개인정보 보호정책에 따라 반드시 atomic(개별 필드)으로 관리되며, 실제 출결 알림, 시스템 접근 로그 등
   * 주요 데이터의 표시에 활용됩니다.
   *
   * 실무 사례에서는 입력값의 정합성(2-50자 사이, 한글/영문 지원) 규칙이 보통 적용됩니다.
   */
  name: string;

  /**
   * 학부모의 이메일(알림 및 인증)입니다. Prisma 테이블에서 유니크 제약을 가지며, 알림 수신, 계정 인증, 비밀번호 찾기 등에서
   * 사용됩니다.
   */
  email: string;

  /** 학부모의 휴대폰 번호입니다. 문자 알림, 2차 인증, 연락처 검증 용도로만 atomic하게 저장됩니다. */
  phone: string;

  /** 회원 최초 생성일시(ISO8601, UTC)로, 감사 및 가입 내역 추적에 사용됩니다. */
  created_at: string & tags.Format<"date-time">;

  /** 회원정보 최근 수정일(ISO8601, UTC)로, 개인정보 변경 이력 감사 및 적시성 검증에 사용됩니다. */
  updated_at: string & tags.Format<"date-time">;
};
export namespace IAttendanceParent {
  /**
   * Attendance_parent 요약(리스트뷰/검색뷰) row 오브젝트 타입입니다. 상세정보/자녀 등은 미포함, 최소 atomic
   * 필드만 포함합니다.
   */
  export type ISummary = {
    /** 학부모 고유 식별자(UUID, PK). attendance_parent.id */
    id: string & tags.Format<"uuid">;

    /** 학부모/보호자 이름. atomic 필드, 요약뷰용. */
    name: string;

    /** 이메일(로그인/알림, 유니크), 요약리스트 표기 필드. */
    email: string;

    /** 핸드폰(알림/연락처), 부모 리스트뷰 표기 필드. */
    phone: string;
  };

  /**
   * 부모(Parent/Guardian) 목록 쿼리/검색 요청DTO 필드 집합. 전체 필드는 atomic/3NF/Validation대로
   * 구성. 일반적으로 PATCH /attendance/parents 등에서 사용.
   */
  export type IRequest = {
    /** 검색 대상 부모가 소속된 학교 ID(FK to attendance_school.id). */
    school_id?: string & tags.Format<"uuid">;

    /** 검색용 부모이름(부분/정확 검색). */
    name?: string;

    /** 검색용 이메일. */
    email?: string & tags.Format<"email">;

    /** 검색용 전화번호. */
    phone?: string;

    /** 해당 부모의 자녀(학생) ID기준 검색(학생-부모 연결성 검증 지원). */
    child_id?: string & tags.Format<"uuid">;

    /** 페이지네이션 파라미터. */
    page?: number & tags.Type<"int32">;

    /** 페이지당 건수. */
    limit?: number & tags.Type<"int32">;

    /** 정렬기준 필드. */
    sort_by?: "created_at" | "updated_at";

    /** 정렬방향. */
    sort_direction?: "asc" | "desc";
  };

  /**
   * 신규 학부모(보호자) 회원 생성 요청 오브젝트. 시스템 내 학부모 등록시 사용.
   *
   * - 모든 필드는 atomic/필수이며, 참조 컬럼(auth_account_id) UUID.
   * - 개인정보 유니크 제약(이메일 중복 불가) 반드시 준수.
   * - Prisma attendance_parent 테이블 생성 요구조건 일치.
   */
  export type ICreate = {
    /**
     * 생성 시 필수. 인증계정(소셜/로컬) 고유 식별자 UUID입니다. Prisma attendance_auth_account와
     * 1:1 참조합니다.
     */
    auth_account_id: string & tags.Format<"uuid">;

    /** 신규 학부모의 실명입니다. 실제 알림, 서비스 제공에 필수적으로 활용됩니다. */
    name: string;

    /** 회원의 이메일 주소 입니다. 유니크(중복x) 제약을 준수합니다. */
    email: string;

    /** 회원의 연락처(핸드폰)입니다. 문자 알림 및 본인연락에 사용됩니다. */
    phone: string;
  };

  /**
   * Attendance_parent(보호자)의 정보 수정 요청 오브젝트
   *
   * - 일부/전체 컬럼(이름/email/phone/auth_account_id) 값 변경용
   * - 모든 값은 atomic
   * - Prisma 유니크 제약, FK조건은 반드시 준수.
   * - 수정 대상 PK(id)는 path/route param에서 입력.
   */
  export type IUpdate = {
    /** 수정할 실명(이름). */
    name?: string;

    /** 수정할 이메일(고유값) */
    email?: string;

    /** 수정할 휴대폰번호(연락처) */
    phone?: string;

    /** 수정시 연결 인증 계정(소셜/로컬) UUID. */
    auth_account_id?: string & tags.Format<"uuid">;
  };
}
