import { tags } from "typia";

/**
 * Confirmation object returned after a successful delete operation on a row
 * such as a post edit, comment, or vote. Used to acknowledge logical deletion
 * in compliance with DELETION business rules and soft delete audit patterns.
 *
 * Implementation refers to standard confirmation feedback for deletion UI—may
 * include audit log data, status, deleted row ID.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IDeleteConfirmation = {
  /**
   * Status message or code confirming deletion. Typically 'deleted' or
   * similar.
   */
  status: string;

  /**
   * ID of the record that was deleted. Serves as evidence of the item for
   * logs or UI deletion confirmation.
   */
  id: string & tags.Format<"uuid">;
};
