import { tags } from "typia";

/**
 * Discussion_board_forum_subcategory는 특정 상위 카테고리 아래에 소속된 포럼 하위 주제 집합을 정의합니다.
 *
 * 예시: '국내정치' 상위 카테고리 아래에 '선거제도', '지역갈등'등의 하위 카테고리들이 존재할 수 있습니다. 하위 카테고리는
 * 포스팅/스레드 그룹핑, UI 네비게이션, 통계 및 관리적 분류 등에 사용됩니다. 이름은 상위 카테고리 내에서 고유해야 하며,
 * 생성/수정/설명 등 메타데이터 및 외래키로 관계를 표현합니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IDiscussionBoardForumSubcategory = {
  /**
   * 하위 카테고리 식별자(UUID). discussion_board_forum_subcategory의 PK입니다. 모든 비즈니스/DB
   * 참조 시 반드시 사용.
   */
  id: string & tags.Format<"uuid">;

  /**
   * 상위 카테고리(discussion_board_forum_category)의 식별자(UUID). 어떤 상위 카테고리 소속인지 명확히
   * 구분되며, FK로 integrity를 유지합니다.
   */
  forum_category_id: string & tags.Format<"uuid">;

  /** 하위 카테고리의 명칭(예시: '통화정책'). UI에 표시됨. Unique(동일 상위 카테고리 내 이름 중복 불가). */
  name: string;

  /** 이 하위 카테고리에 대한 설명 또는 요약. 검색, 목록, 상세 화면 등에 활용됨. null 허용. */
  description?: string | null;

  /** 카테고리 생성 일시(ISO8601/RFC3339). Audit/logging, UI 표시 등에 활용됨. */
  created_at: string & tags.Format<"date-time">;

  /** 마지막 업데이트 일시(ISO8601/RFC3339). */
  updated_at: string & tags.Format<"date-time">;
};
export namespace IDiscussionBoardForumSubcategory {
  /**
   * 토론 게시판의 하위 카테고리(discussion_board_forum_subcategory)에 대한 검색, 필터, 정렬,
   * 페이지네이션 요청 타입입니다.
   *
   * 상위 카테고리, 이름, 생성일 범위 등 다양한 조건으로 하위 카테고리를 조회하기 위해 사용합니다. 페이지네이션, 정렬 등을 지원하며
   * 관리자/모더레이터가 대량으로 조회하거나 UI의 필터되는 목록 제공 시 사용됩니다.
   *
   * 각 속성은 모두 선택적이며, null 또는 미지정 시 해당 조건을 무시합니다.
   */
  export type IRequest = {
    /**
     * 페이지 번호(1부터 시작). 페이지네이션을 위한 선택적 값입니다. 만약 null이면 기본값(1) 또는 서비스 기본 동작에
     * 따름.
     */
    page?: (number & tags.Type<"int32">) | null;

    /**
     * 페이지당 반환될 최대 하위 카테고리 수입니다. 예시: 10, 20, 50, 100 등. null이면 서비스 기본값(일반적으로
     * 20~100) 사용.
     */
    limit?: (number & tags.Type<"int32">) | null;

    /**
     * 특정 상위 카테고리(Forum Category) ID(UUID)를 기준으로 하위 카테고리만 페치하고자 할 때 지정합니다.
     * null이면 전체 하위 카테고리가 대상입니다.
     */
    forum_category_id?: (string & tags.Format<"uuid">) | null;

    /** 하위 카테고리명을 부분일치로 검색합니다. 예를 들어 '정책' 등. null이면 무시. */
    name?: string | null;

    /** 하위 카테고리 생성일(이상) 필터. ISO 8601 포맷. null이면 무시. */
    created_at_from?: (string & tags.Format<"date-time">) | null;

    /** 하위 카테고리 생성일(이하) 필터. ISO 8601 포맷. null이면 무시. */
    created_at_to?: (string & tags.Format<"date-time">) | null;
  };

  /**
   * 새로운 discussion_board_forum_subcategory (포럼 하위 카테고리) 엔티티를 생성하기 위한 입력
   * 타입입니다.
   *
   * Admin/moderator가 상위 카테고리 아래에 새로운 주제 그룹을 추가할 때 사용합니다. 이름과 소속 상위 카테고리는
   * 필수이며, 설명은 선택적으로 제공할 수 있습니다.
   */
  export type ICreate = {
    /** 이 하위 카테고리가 소속될 상위 카테고리의 식별자(UUID). */
    forum_category_id: string & tags.Format<"uuid">;

    /** 신규 생성될 하위 카테고리의 명칭. 동 카테고리 내 중복 불가. 예: '사회복지'. (UI 표시용) */
    name: string;

    /** 신규 생성 하위 카테고리의 설명(선택). null 가능. 예: '복지 정책 관련 토론의 모음'. */
    description?: string | null;
  };

  /**
   * 기존 discussion_board_forum_subcategory(하위 카테고리) 엔티티에 대해 부분/전체 변경을 요청할 때
   * 사용하는 입력타입입니다.
   *
   * Name, description, forum_category_id의 변경 중 원하는 값만 부분적으로 제공 가능하며, null 또는
   * 미지정은 해당 필드 수정 없음 의미.
   */
  export type IUpdate = {
    /** 하위 카테고리명 변경 요청 시 입력. null이면 미변경. 중복 불가(동일 상위 카테고리 내). */
    name?: string | null;

    /** 하위 카테고리 설명 변경. null이면 미변경(eventually nullable, 명시적 null은 설명 삭제). */
    description?: string | null;

    /** 상위 카테고리 ID를 다른 값으로 이동할 때 입력. null이면 미변경. */
    forum_category_id?: (string & tags.Format<"uuid">) | null;
  };
}
