import { tags } from "typia";

/**
 * 디스커션 보드의 시스템 설정 엔터티입니다.
 *
 * Prisma discussion_board_settings 테이블에서 파생되며, 보드 운영에 필요한 기능 토글, 주요 옵션, 정책, 또는
 * 전역 변수 상태를 안전하게 관리할 수 있게 설계되었습니다. 각 설정은 유일한 키를 바탕으로 값(텍스트)과 설명 및 메타데이터를
 * 보유합니다.
 *
 * 관리 UI, 자동화 파이프라인, 운영 분석에서 활용될 수 있으며, 시스템 변경 시 생성/수정 이력 파악을 위해 타임스탬프가 포함됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IDiscussionBoardSetting = {
  /**
   * 고유 식별자(UUID). 이 설정 레코드를 고유하게 식별합니다.
   *
   * Prisma 스키마 discussion_board_settings.id에서 유래했습니다. 시스템 내에서 각 설정을 참조할 때
   * 필수적입니다.
   */
  id: string & tags.Format<"uuid">;

  /**
   * 설정의 고유 키 값(예: 'registration_open').
   *
   * Prisma discussion_board_settings.setting_key 컬럼(UNIQUE)에서 유래했습니다. 각 설정은 이
   * 키로 식별되어 중복이 불가능합니다. 시스템 기능 토글, 등록, 정책 등 다양한 목적으로 사용됩니다.
   */
  setting_key: string;

  /**
   * 설정의 현재 값이며 자유 텍스트로 저장됩니다.
   *
   * Prisma 스키마 discussion_board_settings.setting_value에서 유래했습니다. 설정의 의미와 실제
   * 시스템 적용 값을 저장합니다.
   */
  setting_value: string;

  /**
   * (선택) 이 설정이 제어(설정) 하는 바에 대한 설명.
   *
   * Prisma discussion_board_settings.description에서 유래했습니다. 상세한 설명이 포함될 수 있으며,
   * null이 허용됩니다.
   */
  description?: string | null;

  /**
   * 설정 레코드 생성 시각. ISO 8601 포맷 사용.
   *
   * Prisma discussion_board_settings.created_at에서 유래했습니다.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * 설정 레코드가 마지막으로 수정된 시각. ISO 8601 포맷입니다.
   *
   * Prisma discussion_board_settings.updated_at에서 유래했습니다.
   */
  updated_at: string & tags.Format<"date-time">;
};
export namespace IDiscussionBoardSetting {
  /**
   * 설정 목록의 검색/필터/정렬/페이징 조건을 전달하는 요청 타입. 관리자 대시보드나 API에서 다양한 조건으로 설정을 검색/정렬할 때
   * 사용됩니다.
   */
  export type IRequest = {
    /** 설정키 필터(부분 또는 완전 일치 검색). */
    setting_key?: string | null;

    /** 설정 생성일 기준 검색 범위(시작). ISO8601. */
    created_at_start?: (string & tags.Format<"date-time">) | null;

    /** 설정 생성일 기준 검색 범위(종료). ISO8601. */
    created_at_end?: (string & tags.Format<"date-time">) | null;

    /** 설정 수정일 기준 검색 범위(시작). ISO8601. */
    updated_at_start?: (string & tags.Format<"date-time">) | null;

    /** 설정 수정일 기준 검색 범위(종료). ISO8601. */
    updated_at_end?: (string & tags.Format<"date-time">) | null;

    /** 정렬 기준 필드명(예: setting_key, created_at 등). */
    sort?: string | null;

    /** 정렬 순서(오름차순/내림차순). */
    order?: "asc" | "desc" | null;

    /** 페이지 번호. */
    page?: (number & tags.Type<"int32">) | null;

    /** 페이지당 반환 개수(기본 100). */
    limit?: (number & tags.Type<"int32">) | null;
  };

  /**
   * 새로운 보드 설정을 생성할 때 사용하는 객체입니다. 관리자가 UI나 백엔드에서 신규 옵션, 플래그를 생성 시 제출합니다.
   *
   * 필수 입력은 고유 키 및 값이며, 설명은 선택입니다. Prisma discussion_board_settings ICreate
   * 용도로 설계되었습니다.
   */
  export type ICreate = {
    /** 등록할 설정의 고유 키 값. Prisma setting_key(UNIQUE) 컬럼의 비즈니스 요구를 따릅니다. */
    setting_key: string;

    /** 설정 텍스트 값. Prisma setting_value 컬럼을 참조합니다. */
    setting_value: string;

    /**
     * (선택) 이 설정의 목적 또는 설명입니다. Prisma
     * discussion_board_settings.description에서 유래했습니다. 비어있거나 null 허용됩니다.
     */
    description?: string | null;
  };

  /**
   * 기존 보드 설정을 수정할 때 사용하는 업데이트 객체입니다.
   *
   * 관리자는 이 타입을 통해 텍스트 값, 설명, 드물게 키까지 수정할 수 있습니다. Prisma
   * discussion_board_settings IUpdate 용도입니다.
   */
  export type IUpdate = {
    /**
     * 설정의 고유 키(변경 가능). Prisma setting_key 필드를 참조합니다. 변경 시 키의 유일성이 보장되어야 하며,
     * 시스템적 제약이 많으므로 주의가 필요합니다.
     */
    setting_key?: string;

    /** 설정의 새로운 값입니다. 기존 setting_value의 업데이트용. */
    setting_value?: string;

    /** (선택) 이 설정의 목적 및 설명. Prisma 컬럼에서 파생됨. null을 허용합니다. */
    description?: string | null;
  };
}
