import { tags } from "typia";

/**
 * 구독 엔티티. 사용자가 스레드, 섹션, 태그 등의 콘텐츠를 팔로우할 때 생성되는 관계 모델입니다.
 *
 * Prisma discussion_board_subscriptions 테이블 구조 및 주석을 참고하십시오. 이 엔티티는 단순히 멤버-대상 간
 * 구독 정보를 원자적으로 저장하며, 중복(동일 사용자-타입-대상)에 대해 유니크 제약 조건을 가집니다. 예: 한 사용자는 동일한 스레드를 두
 * 번 이상 구독할 수 없습니다.
 *
 * 모든 구독은 생성 시점, 팔로우 동작 주체 ID, 타겟 타입/ID를 반드시 명시해야 하며, 생성된 구독 객체는 관리/사용자 포털에
 * 노출되거나 알림 정책에 활용됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IDiscussionBoardSubscription = {
  /**
   * 고유 식별자입니다. Prisma discussion_board_subscriptions.id 컬럼 주석을 참조하십시오.
   *
   * 각 구독 관계는 시스템 내에서 고유하게 식별되어야 하며, 이 필드는 그런 고유성을 보장합니다. 예시:
   * '3eab8f08-c591-4ed5-ae2e-ac513b1234ef'. 관리자 및 사용자 인터페이스에서 참조됩니다.
   */
  id: string & tags.Format<"uuid">;

  /**
   * 구독자의 ID입니다(Prisma discussion_board_members.id 참조).
   *
   * 이 필드는 구독 소유자를 기준으로 하여 어떤 사용자가 어떤 대상을 팔로우하고 있는지 추적합니다. 예:
   * 'c715e749-f471-421b-ad29-ed43ffadc3e3'. 기본적으로 인증된 사용자 본인의 구독만 검색 및 조작할 수
   * 있습니다.
   */
  member_id: string & tags.Format<"uuid">;

  /**
   * 구독 대상(타입). Prisma discussion_board_subscriptions.target_type 컬럼의 요구사항을
   * 따릅니다.
   *
   * 예: 'thread', 'section', 'tag' 등의 구분형 문자열입니다. 시스템은 이후 새로운 타입 확장도 지원합니다.
   * 필수값입니다.
   */
  target_type: string;

  /**
   * 구독 대상의 고유 식별자입니다. (예: 특정 스레드/섹션/태그 등)
   *
   * 타입에 따라 연결된 테이블이 달라질 수 있습니다. 예: '74f8ce2c-089e-4923-b7a6-3283e18c4dee'.
   */
  target_id: string & tags.Format<"uuid">;

  /**
   * 구독 생성 시각. Prisma discussion_board_subscriptions.created_at 컬럼 참조.
   *
   * 사용자, 관리자 인터페이스에서 최근 신규 구독을 정렬 시 활용합니다. ISO8601 형식, 예시:
   * '2024-07-22T15:12:45.123Z'.
   */
  created_at: string & tags.Format<"date-time">;
};
export namespace IDiscussionBoardSubscription {
  /**
   * Discussion_board_subscriptions(구독) 엔티티 검색/필터/페이지네이션용 요청입니다. 구독센터, 관리페이지
   * 등에서 사용.
   */
  export type IRequest = {
    /** 구독 컬럼별 필터. Prisma discussion_board_subscriptions 컬럼별. */
    filter?: {
      /** 구독 엔트리의 주체/회원 UUID. */
      member_id?: string & tags.Format<"uuid">;

      /** 구독 대상 타입(예: thread, section, tag 등). */
      target_type?: string;

      /** 구독 리소스의 고유 식별자(UUID). */
      target_id?: string & tags.Format<"uuid">;

      /** 해당 일시 이후 생성된 구독만 조회. */
      created_from?: string & tags.Format<"date-time">;

      /** 해당 일시 이전에 생성된 구독만 조회. */
      created_to?: string & tags.Format<"date-time">;
    };

    /** 페이지 번호(1부터 시작). */
    page?: number & tags.Type<"int32">;

    /** 한 페이지당 데이터 개수. */
    limit?: number & tags.Type<"int32">;

    /** 정렬 옵션(최신순, 타입, 리소스 등). */
    sort?: string;
  };

  /**
   * 구독 생성 요청 스키마. 사용자가 새로운 리소스(스레드/섹션/태그 등)를 팔로우(구독)할 때 전달하는 정보 구조입니다.
   *
   * Prisma discussion_board_subscriptions 테이블의 제약 및 주석을 참고하십시오. 본 요청은 인증된
   * 사용자의 본인 기준으로 유효합니다. 'member_id'는 세션에서 추론됩니다.
   *
   * 최소한 구독 대상 타입과 해당 대상의 식별자를 필수로 포함해야 하며, 해당 대상이 실제로 존재해야 합니다.
   */
  export type ICreate = {
    /**
     * 구독 대상 타입. 예: 'thread', 'section', 'tag' 등으로 제한될 수 있습니다. Prisma
     * discussion_board_subscriptions.target_type 컬럼 주석과 일치.
     *
     * 이 값은 서비스 정책에 따라 확장 가능하며, 클라이언트 UI에서 내부 값이 동적으로 결정될 수 있습니다.
     */
    target_type: string;

    /**
     * 구독하고자 하는 대상의 고유 식별자 값. Prisma
     * discussion_board_subscriptions.target_id 컬럼 주석을 참고하십시오.
     *
     * 해당 타입의 실제 리소스(스레드/섹션/태그 등)가 존재해야 하며, 대상의 활성화 상태/소유권 등은 비즈니스 규칙에 따라 검증
     * 후 등록됩니다.
     */
    target_id: string & tags.Format<"uuid">;
  };

  /**
   * 구독 레코드 갱신용 스키마입니다. 대부분 알림 정책 등의 프리미티브 옵션이 확장될 때 제한적 갱신에 사용되며, 실제로는 주로
   * 삭제(구독 해제) 시 이용됩니다.
   *
   * Prisma discussion_board_subscriptions 테이블 컬럼 주석과 실무적 제약을 참고하세요. 현재 구조상 바뀔
   * 파라미터는 극히 제한적입니다.
   */
  export type IUpdate = {
    /**
     * 갱신 대상의 타입 값. 다양한 알림 정책 등 변화가 있는 경우에만 변경함. (구독 타입 변경 자체는 실무상 거의 쓰이지
     * 않음)
     */
    target_type?: string;
  };
}
