import { tags } from "typia";

/**
 * Discussion_board_role_assignment 엔터티(롤 할당 단일 건)에 대한 세부 정보 타입입니다.
 *
 * 이 타입은 특정 유저가 언제 어떤 역할을 할당/회수받았는지에 대한 사건 이력을 그대로 구조화합니다. RBAC(역할 기반 접근제어) 정책,
 * 관리자 권한 부여, 롤 히스토리, 감사 로그 등에 실제 사용됩니다. 프리즈마 스키마의 컬럼과 1:1로 매핑되며, 각 필드는 상세 주석이
 * 첨부되어 가이드합니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IDiscussionBoardRoleAssignment = {
  /**
   * 롤 할당 레코드 고유 식별자 (UUID)
   *
   * 프리즈마 discussion_board_role_assignment 테이블의 기본 키입니다. 각 롤 할당은 이 값을 기준으로
   * 참조하거나 단일 상세 조회를 진행합니다.
   */
  id: string & tags.Format<"uuid">;

  /**
   * 권한 할당 대상 유저의 고유 식별자 (UUID)
   *
   * 실제 discussion_board_user를 참조하며, 사용자별 롤 변경 및 권한 조회의 기준점이 됩니다.
   */
  user_id: string & tags.Format<"uuid">;

  /**
   * 할당된 롤 유형(예: member, moderator, admin, guest)
   *
   * 시스템에서 허용하는 롤 값만 입력해야 하며, RBAC 정책 및 프리즈마 ENUM과 연동됩니다.
   */
  role_type: string;

  /**
   * 이 롤이 유저에게 할당된 시각(ISO 8601 timestamp)
   *
   * 정확한 역할 시작일 및 변경 이력을 감사(audit) 용도로 제공합니다.
   */
  assigned_at: string & tags.Format<"date-time">;

  /**
   * 롤 권한 회수가 발생한 시점 (없을 경우 null)
   *
   * 로그성 데이터로, 해지된 롤은 별도 관리 및 분석에 활용합니다.
   */
  revoked_at?: (string & tags.Format<"date-time">) | null;
};
export namespace IDiscussionBoardRoleAssignment {
  /**
   * Role assignment list/search filter object, supporting pagination,
   * assignment, and revocation status queries. Applies to PATCH
   * /discussionBoard/roleAssignments and similar endpoints. Direct reference
   * to discussion_board_role_assignment structure.
   */
  export type IRequest = {
    /** Page number to retrieve in role assignment listing/search. */
    page?: (number & tags.Type<"int32">) | null;

    /** Maximum number of role assignments to return per page. */
    limit?: (number & tags.Type<"int32">) | null;

    /** Filter records by user UUID (role assignment owner). */
    user_id?: (string & tags.Format<"uuid">) | null;

    /**
     * Filter/search by specific role assignment ('member', 'admin',
     * 'moderator', 'guest').
     */
    role_type?: string | null;

    /**
     * Lower inclusive bound of role assignment date for filter/range
     * queries.
     */
    assigned_from?: (string & tags.Format<"date-time">) | null;

    /**
     * Upper inclusive bound of role assignment date for filter/range
     * queries.
     */
    assigned_to?: (string & tags.Format<"date-time">) | null;

    /** Restrict to revoked (false), active (true) or all role assignments. */
    revoked?: boolean | null;
  };

  /**
   * 새로운 롤 권한 할당 생성 요청 타입입니다.
   *
   * 프리즈마의 discussion_board_role_assignment 생성 작업에 사용되며, 대상 유저, 부여할 롤 타입, 시작
   * 일시, 해지 시점(선택)을 명확히 선언해야 합니다. 관리자나 자동화 시스템(예: 정책에 의한 자동 롤 권한)에서 활용됩니다.
   */
  export type ICreate = {
    /**
     * 권한을 할당할 타깃 유저의 고유 식별자 (UUID)
     *
     * 회원 가입 또는 기존 유저에게 특정 역할을 부여할 때 이를 지정합니다.
     */
    user_id: string & tags.Format<"uuid">;

    /**
     * 새로 부여하고자 하는 롤 타입(예: member, moderator, admin, guest)
     *
     * 정확히 허용된 값만 입력해야 합니다. 관리자 패널에서는 ENUM 선택을 지원합니다.
     */
    role_type: string;

    /**
     * 해당 롤의 부여 시각(UTC 표준, ISO 8601)
     *
     * 즉시 할당이면 현재 시각, 이력 통합시 과거값을 선택할 수 있습니다.
     */
    assigned_at: string & tags.Format<"date-time">;

    /**
     * 롤 권한 해지(회수)가 예정 또는 즉시 반영되는 뉴스(없을 경우 null)
     *
     * 권한 유지 기간이 제한된 특별 롤(임시 권한) 부여에 활용됩니다.
     */
    revoked_at?: (string & tags.Format<"date-time">) | null;
  };

  /**
   * 기존 롤 권한 할당 엔터티의 정보 수정 요청 타입입니다.
   *
   * 하나의 롤 할당을 식별(경로 파라미터 등)하여, 롤 타입(역할) 또는 회수 일시(revoked_at)를 변경할 때 사용합니다. 롤
   * 타입 미변경시 revoked_at만 갱신 가능합니다.
   */
  export type IUpdate = {
    /**
     * 변경하려는 롤 유형(예: member, admin, moderator 등)
     *
     * 관리자 또는 정책에 따라 롤 타겟이 바뀔 때 입력합니다.
     */
    role_type: string;

    /**
     * 롤 회수/해지 시점 (없으면 null)
     *
     * 회수 일자를 등록/수정하여 롤 종료나 임시권한 만료를 구현합니다.
     */
    revoked_at?: (string & tags.Format<"date-time">) | null;
  };
}
