import { tags } from "typia";

/**
 * Represents a normalized organization/team record as defined in the Prisma
 * organizations table. This entity supports grouping of users, teams, or
 * moderation groups for future scalability and management, as outlined in the
 * requirements documentation and ERD diagrams.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IOrganization = {
  /**
   * Unique identifier for the organization/time/group as held in the
   * organizations table. Used as the row primary key and for all admin/audit
   * references.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Organization/team/group name as defined in the schema. This must be
   * unique per platform business rules and is indexed for searching,
   * assignment, and navigation in advanced UI workflows.
   */
  name: string;

  /**
   * Long-form, human-readable description of group or organization's purpose,
   * used for admin reference, onboarding, or help text, and is nullable for
   * optional expansion.
   */
  description?: string;
};
export namespace IOrganization {
  /**
   * Standard search, filter, and pagination payload for listing
   * organization/team/group records. Follows the atomic and normalized
   * structure of the organizations table as per system and business rules,
   * supporting admin and audit requirements.
   */
  export type IRequest = {
    /**
     * A text-filter against organization names, used for searching,
     * filtering, or autocompletion in admin UIs. Drawn directly from the
     * 'name' column in organizations table and enforced unique by schema.
     */
    name?: string;

    /**
     * Filters for organizations list by creation date/time. Used to
     * manage/monitor group/team creation in audit scenarios.
     */
    created_at_range?: {
      /**
       * Start (inclusive) timestamp for creation date filtering of
       * organizations. Follows audit/business logic for board/team
       * management.
       */
      from?: string & tags.Format<"date-time">;

      /**
       * End (inclusive) timestamp for creation date filtering of
       * organizations. Supports audit scenarios and scalability.
       */
      to?: string & tags.Format<"date-time">;
    };

    /**
     * Ordering attribute for sorting organization list pages. Ensures
     * flexibility for admin and UI use by referencing only atomic, indexed
     * columns in organizations.
     */
    sort_by?: "name" | "created_at";

    /**
     * Ordering direction (ascending or descending). Defaults to ascending;
     * critical for predictable UX and audit traceability in organization
     * management.
     */
    sort_order?: "asc" | "desc";

    /**
     * Page number for pagination (1-based index). Follows standard
     * admin/API entity-listing practice in all platform UIs.
     */
    page?: number &
      tags.Type<"int32"> &
      tags.JsonSchemaPlugin<{
        format: "int32";
      }>;

    /**
     * Number of entries per page for pagination. Enforces hard/soft limits
     * per business rules to control API result size.
     */
    limit?: number &
      tags.Type<"int32"> &
      tags.JsonSchemaPlugin<{
        format: "int32";
      }>;
  };

  /**
   * Payload for creating a new organization/group/team. All required atomic
   * attributes are drawn from the organizations table in the schema and must
   * pass platform validation (unique names, etc.).
   */
  export type ICreate = {
    /**
     * The unique name for the new organization/group/team, following the
     * organizations table uniqueness rule in the Prisma schema. Used to
     * label and refer to the new entity in admin and user-facing UIs.
     */
    name: string;

    /**
     * Optional long-form description of purpose, membership, or other
     * context for the new organization/team. Populates the organizations
     * table nullable description field for UI/business clarity.
     */
    description?: string;
  };

  /**
   * 조직(teams)의 정보 수정용 타입입니다. 이 타입은 Prisma organizations 테이블의 데이터 구조에 기반하며,
   * 조직명을 고유하게 유지하면서 설명을 업데이트할 수 있도록 설계되었습니다.
   *
   * 조직명(name)은 필수이며, description(설명)은 선택적입니다. RBAC 및 그룹 관리에 활용됩니다.
   */
  export type IUpdate = {
    /**
     * 조직의 이름입니다.
     *
     * Prisma의 organizations.name 컬럼에서 유래되었습니다. 이름은 고유해야 하며, 그룹 라벨 지정, RBAC
     * 또는 향후 SSO 기능을 위해 사용됩니다. 예: '대한민국 경제포럼'.
     */
    name: string;

    /**
     * 조직의 간략한 설명입니다.
     *
     * Prisma의 organizations.description 컬럼에서 유래되었습니다. 관리자 및 사용자를 위한 조직의
     * 설명이나 미션을 전달합니다.
     */
    description?: string | null;
  };
}
