import { IPage } from "./IPage";
import { IUser } from "./IUser";

/**
 * 사용자 검색 결과의 페이징 컨테이너입니다.
 *
 * Pagination(페이징 메타정보)와 data(사용자 목록)를 제공합니다. data 배열은 IUser 타입을 사용합니다.
 *
 * Prisma users 테이블 전체 집합의 리스트 요청, 다양한 필터 및 정렬 사용자 시나리오에 적합합니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIUser = {
  /** 페이징 처리 관련 메타필드(현 페이지, 페이지 크기, 전체 레코드 수 등). */
  pagination: IPage.IPagination;

  /** 사용자 계정의 상세 정보 리스트입니다. */
  data: IUser[];
};
