import { IPage } from "./IPage";
import { IDiscussionBoardAdministrator } from "./IDiscussionBoardAdministrator";

/**
 * A page of administrator assignments, with pagination metadata and array of
 * administrator assignment objects.
 *
 * Each record links an admin assignment to a member entity.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIDiscussionBoardAdministrator = {
  pagination: IPage.IPagination;

  /** List of administrator assignments on this page. */
  data: IDiscussionBoardAdministrator[];
};
