import { IPage } from "./IPage";
import { IPoll } from "./IPoll";

/**
 * Paginated search results for polls using IPage<T> container pattern. Returns
 * polls for admin analytic dashboards, audit UI, and moderation overview.
 *
 * This is used wherever lists of polls are needed (vote management, UI browse,
 * etc). Each poll is returned as an IPoll object. Follows same field layout as
 * IPage for pagination, counts, and results.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIPoll = {
  /**
   * Results pagination metadata (see IPage.IPagination in standard
   * components).
   */
  pagination: IPage.IPagination;

  /**
   * Array of poll objects for this page. Each element describes an atomic
   * poll and its basic relations per schema/IPoll.
   */
  data: IPoll[];
};
