import { IPage } from "./IPage";
import { IAttendanceSocialAccount } from "./IAttendanceSocialAccount";

/**
 * 소셜 계정 매핑 표준 페이지네이션 결과 구조. data=소셜계정 배열, pagination=메타데이터(전체건수, 현재페이지 등)
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIAttendanceSocialAccount = {
  pagination: IPage.IPagination;

  /** 소셜 계정 매핑 엔터티 복수개 배열 */
  data: IAttendanceSocialAccount[];
};
