import { IPage } from "./IPage";
import { IOrganization } from "./IOrganization";

/**
 * Paginated list of organization entities (groups/teams) for admin and audit
 * purposes. All results follow the normalized organizations table schema,
 * ensuring comprehensive and scalable UI/API workflows.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIOrganization = {
  pagination: IPage.IPagination;

  /**
   * List of organization records for the requested page, fully matching the
   * organizations table schema and normalized for business/audit workflows.
   */
  data: IOrganization[];
};
