import { IPage } from "./IPage";
import { IDiscussionBoardReport } from "./IDiscussionBoardReport";

/**
 * Paginated result schema for moderation reports in the discussion board.
 * Follows IPage<T> pattern, where T is the report entity defined by
 * `IDiscussionBoardReport`. Provides audit, workflow, and detail views in
 * dashboards or compliance UIs.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIDiscussionBoardReport = {
  pagination: IPage.IPagination;

  /** Data array listing individual report records for this page of the result. */
  data: IDiscussionBoardReport[];
};
