import { IPage } from "./IPage";
import { IDiscussionBoardForumSubcategory } from "./IDiscussionBoardForumSubcategory";

/**
 * Discussion_board_forum_subcategory를 대상으로 한 페이징 응답 타입입니다. pagination에는 현재 페이지
 * 정보(페이지 번호, 페이지 크기, 전체 레코드, 전체 페이지 수)가 포함되고, data에는 실제 개별 하위 카테고리 엔티티가 배열로
 * 반환됩니다.
 *
 * 이 타입은 특정 검색 또는 필터 조건에 부합하는 하위 카테고리들의 결과 목록 제공(예: UI의 하위 카테고리 목록)에 표준적으로
 * 사용됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageDiscussionBoardForumSubcategory = {
  pagination: IPage.IPagination;

  /** 해당 페이지에 포함된 하위 카테고리 레코드 목록입니다. */
  data: IDiscussionBoardForumSubcategory[];
};
