import { IPage } from "./IPage";
import { IDiscussionBoardPostVersion } from "./IDiscussionBoardPostVersion";

/**
 * Paginated result set for discussion board post versions (edit history, audit
 * trail).
 *
 * Includes an array of post version records and page metadata; used for listing
 * or searching post edits/audits as per board requirements.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIDiscussionBoardPostVersion = {
  pagination: IPage.IPagination;

  /**
   * Array of post version records for this page of history; each entry
   * corresponds to one edit iteration (snapshot) as stored by
   * discussion_board_post_versions table. All details as per the
   * IDiscussionBoardPostVersion schema.
   */
  data: IDiscussionBoardPostVersion[];
};
