import { IPage } from "./IPage";
import { IDiscussionBoardThread } from "./IDiscussionBoardThread";

/**
 * Paginated result container for discussion board thread listings.
 *
 * Implements the IPage<T> generic form for paginated endpoints as described in
 * OpenAPI and discussed in the requirements and standard pagination practices.
 * This type always includes page metadata and array of thread records as
 * payload.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIDiscussionBoardThread = {
  /**
   * Page information.
   *
   * Describes the state and boundaries of this page of thread records,
   * including the current page number, limit per page, total records matching
   * query, and total page count (ceiling division). Corresponds to paging
   * controls on UI and supports efficient client-side navigation. See
   * business rules for maximum/minimum limits.
   */
  pagination: IPage.IPagination;

  /**
   * Array of thread summary/record objects for this page. Each record follows
   * the complete or summary specification for a 'discussion_board_thread' as
   * derived from the OpenAPI operation and Prisma schema.
   */
  data: IDiscussionBoardThread[];
};
