import { IPage } from "./IPage";
import { IAttendanceTeacher } from "./IAttendanceTeacher";

/**
 * 교사(Teacher) 목록 및 페이지네이션이 결합된 표준 리스트 응답 DTO 객체입니다.
 *
 * IPage<T> 인터페이스 패턴을 따르며, pagination은 현재페이지/전체갯수 등, data는
 * IAttendanceTeacher.ISummary[]로 각 레코드의 요약 내용만 포함합니다.
 *
 * Prisma attendance_teacher 엔티티의 검색/리스트/관리 페이지 등에서 반환 표준을 제공합니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageAttendanceTeacher = {
  pagination: IPage.IPagination;

  /** 해당 페이지에 대응하는 교사(요약) 객체들의 배열. 각 원소는 ISummary(필수 주요 필드만)를 참조. */
  data: IAttendanceTeacher.ISummary[];
};
