import { IPage } from "./IPage";
import { IComment } from "./IComment";

/**
 * A paginated list of comment summaries, including pagination metadata (page,
 * limit, total, etc.) and a summary array.
 *
 * Combines IPage (standard) with IComment.ISummary as required by comment
 * browsing scenarios.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIComment = {
  pagination: IPage.IPagination;

  /**
   * A list of comment summary objects on the current page.
   *
   * Each item is a concise representation of a comment as described in
   * business use-cases: post/reply thread listings.
   */
  data: IComment.ISummary[];
};
