import { IPage } from "./IPage";
import { IDiscussionBoardRoleAssignment } from "./IDiscussionBoardRoleAssignment";

/**
 * 롤 할당 레코드의 페이지네이션된 컨테이너입니다.
 *
 * 이 타입은 페이징된 discussion_board_role_assignment 조회 결과를 구조화된 형태로 제공합니다. 관리자/UI
 * 대시보드에서 롤 권한 이력 목록을 표시하거나 통계 분석, 대량 권한 작업, RBAC(역할 기반 접근제어) 정책 검토 시 활용됩니다.
 * 내부적으로 표준 IPage 구조를 따릅니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIDiscussionBoardRoleAssignment = {
  /**
   * 페이지네이션 정보를 포함합니다.
   *
   * 이 객체는 현재 페이지, 페이지당 항목 수, 총 레코드 수 및 전체 페이지 수 등 요청 데이터의 페이징 상태를 상세히 설명합니다.
   */
  pagination: IPage.IPagination;

  /**
   * 페이지네이션 된 롤 할당 목록입니다.
   *
   * 각 항목은 discussion_board_role_assignment의 세부 정보를 모두 포함하며, 검색 조건에 따라
   * 필터링/정렬됩니다.
   */
  data: IDiscussionBoardRoleAssignment[];
};
