import { IPage } from "./IPage";
import { IDiscussionBoardUserSetting } from "./IDiscussionBoardUserSetting";

/**
 * Container for paged result sets of user settings
 * (discussion_board_user_setting).
 *
 * Includes both metadata for the results page and the data array for user
 * preferences records.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIDiscussionBoardUserSetting = {
  /** Paging metadata for the result set of user settings records. */
  pagination: IPage.IPagination;

  /** Array of user setting objects as returned by the page request. */
  data: IDiscussionBoardUserSetting[];
};
