import { IPage } from "./IPage";
import { IDiscussionBoardThread } from "./IDiscussionBoardThread";

/**
 * Discussion_board_thread 테이블의 스레드 레코드를 페이지 단위로 반환할 때 사용하는 표준 데이터 컨테이너입니다.
 * pagination에는 현재 페이징 정보가, data에는 실제 스레드 상세 배열이 반환됨.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageDiscussionBoardThread = {
  pagination: IPage.IPagination;

  /** 해당 페이지 내 반환되는 토론 스레드 레코드 배열. */
  data: IDiscussionBoardThread[];
};
