import { IPage } from "./IPage";
import { IAttendanceAttendanceMethod } from "./IAttendanceAttendanceMethod";

/**
 * 출석 방식 페이징+목록 응답 타입
 *
 * Pagination(페이징 정보)와 data(출석 방식 엔트리 배열)로 구성되어, 검색/조회 결과의 구조적 전달에 사용합니다. IPage
 * 표준 구조에 맞춤형으로 출석 방식 데이터(IAttendanceAttendanceMethod) 즉, 한 페이지의 모든 레코드가 포함됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageAttendanceAttendanceMethod = {
  pagination: IPage.IPagination;

  /**
   * 해당 페이지에 해당하는 출석 방식(AttendanceAttendanceMethod) 배열입니다. 각 방식 엔트리에는 PK,
   * method_name, description 등의 정보가 포함됩니다.
   */
  data: IAttendanceAttendanceMethod[];
};
