import { IPage } from "./IPage";
import { IPostReport } from "./IPostReport";

/**
 * Paginated result set for post reports, returned from admin/moderator report
 * list endpoints.
 *
 * Contains both the paging metadata and each individual post report for this
 * query.
 *
 * Tied to the moderation workflow and audit trails.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIPostReport = {
  pagination: IPage.IPagination;

  /** Array of post report record objects for the page. */
  data: IPostReport[];
};
