import { IPage } from "./IPage";
import { IDiscussionBoardCommentAttachment } from "./IDiscussionBoardCommentAttachment";

/**
 * Paginated result set for comment attachments. Contains page info and a list
 * of attachment entities. Used for listing, searching, and displaying
 * attachments on comments.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIDiscussionBoardCommentAttachment = {
  pagination: IPage.IPagination;
  data: IDiscussionBoardCommentAttachment[];
};
