import { IPage } from "./IPage";
import { IRoleAssignment } from "./IRoleAssignment";

/**
 * Paginated container for role assignment records. Used as a base response for
 * list/search endpoints on role assignments table.
 *
 * Includes both result data and detailed pagination info in line with IPage
 * semantics, supporting scalable and transparent audit/admin queries.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIRoleAssignment = {
  pagination: IPage.IPagination;

  /**
   * List of role assignment records for the current page. Each entry is fully
   * normalized and adheres to the 'role_assignments' schema constraints and
   * business rules.
   */
  data: IRoleAssignment[];
};
