import { IPage } from "./IPage";
import { IDiscussionBoardPost } from "./IDiscussionBoardPost";

/**
 * Paginated result type for discussion board posts. This type encapsulates a
 * collection of posts (records of type IDiscussionBoardPost) along with
 * pagination metadata. It is used in API responses for post listing and search
 * endpoints.
 *
 * Follows the IPage<T> generic container pattern, specifically for discussion
 * board posts. Reflects the Prisma schema for posts plus infrastructure for
 * paged data transfer. See board requirements (Features/Workflow/Technical) for
 * end-to-end paginated exchange details.
 *
 * This type includes both the array of individual post records and a nested
 * description of pagination state (such as page size, number, total records,
 * etc). No extra statistics or post-count aggregates are returned here; for
 * analytics, refer to board stats endpoints.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIDiscussionBoardPost = {
  pagination: IPage.IPagination;

  /**
   * Array of discussion board posts for this page of results.
   *
   * Each entry in this array is a fully hydrated post record conforming to
   * the IDiscussionBoardPost schema, including safe post metadata but never
   * containing sensitive actor credentials or deleted/private content.
   *
   * Array may be empty if there are no posts for this page.
   */
  data: IDiscussionBoardPost[];
};
