import { IPage } from "./IPage";
import { IAttendanceAuthAccount } from "./IAttendanceAuthAccount";

/**
 * 인증계정(auth_account) 목록형 페이징 결과입니다.
 *
 * 페이지 정보와 해당 페이지의 계정 개별 레코드 배열(data)을 포함합니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIAttendanceAuthAccount = {
  pagination: IPage.IPagination;

  /** 인증계정(IAttendanceAuthAccount) 배열. */
  data: IAttendanceAuthAccount[];
};
