import { IPage } from "./IPage";
import { IModerationLog } from "./IModerationLog";

/**
 * Paginated response schema for moderation logs queries. Each entry represents
 * a single moderation action, and page metadata aids dashboard, analytics, and
 * transparency panels. Implements requirements for audit trails and
 * role/diversity review of moderation acts.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIModerationLog = {
  pagination: IPage.IPagination;

  /**
   * List of moderation log records on this page—auditable atomic records
   * mapped from the moderation_logs table.
   */
  data: IModerationLog[];
};
