import { IPage } from "./IPage";
import { IDiscussionBoardMention } from "./IDiscussionBoardMention";

/**
 * Mention(사용자 언급) 목록을 페이지 단위로 반환하는 패키지 컨테이너 스키마.
 *
 * IPage 구조에 맞추어 pagination(페이지정보), data(실제 레코드 목록)를 반환합니다. UI/백엔드 API에서 집계용, 무한
 * 스크롤, 페이지 인덱서와 사용됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIDiscussionBoardMention = {
  pagination: IPage.IPagination;

  /** 해당 페이지에 포함된 Mention 레코드 목록. 각 아이템은 상세 Mention 엔티티로 아래 참조 */
  data: IDiscussionBoardMention[];
};
