import { IPage } from "./IPage";
import { IDiscussionBoardAttachment } from "./IDiscussionBoardAttachment";

/**
 * Paginated container type for full attachment records, supporting endpoints
 * returning complete metadata and audit fields for attachment lists. Used for
 * admin, export, and system review APIs—do not use for public user listing,
 * which should use the summary form.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIDiscussionBoardAttachment = {
  /**
   * Paging metadata for attachment list results. See IPage.IPagination for
   * details.
   */
  pagination: IPage.IPagination;

  /**
   * Array of full attachment objects (includes all metadata). For API
   * endpoints needing every field for management or export.
   */
  data: IDiscussionBoardAttachment[];
};
export namespace IPageIDiscussionBoardAttachment {
  /**
   * Paginated container for remote summary listings of attachments, as
   * returned by attachment search/list endpoints. Carries summary records for
   * display in UI attachment lists or mod/admin content review.
   * Metadata-only; does not include actual file contents. Designed for
   * efficient result pages.
   */
  export type ISummary = {
    /**
     * Paging information block for the attachment summary results. Contains
     * page number, size, total records, and page count.
     */
    pagination: IPage.IPagination;

    /**
     * Array of summary records of attachments for the current page. Each
     * entry represents metadata for a single attachment (not the full
     * object).
     */
    data: IDiscussionBoardAttachment.ISummary[];
  };
}
