import { IPage } from "./IPage";
import { INotification } from "./INotification";

/**
 * Paginated array of notifications, following the IPage<T> pattern, with
 * INotification as the data element. The pagination field summarizes
 * current/start/total info per Prisma & OpenAPI standards. Used in notification
 * inbox/search APIs.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageINotification = {
  pagination: IPage.IPagination;

  /** Array of notification objects matching the query (see INotification). */
  data: INotification[];
};
