import { IPage } from "./IPage";
import { IAttendanceStatsStudentSummary } from "./IAttendanceStatsStudentSummary";

/**
 * 학생별 기간집계 통계 목록 페이지네이션 구조. 대시보드, 진도 집계, 위험학생 Analytics, 진도/출석 관리 등 용도에 사용.
 *
 * Data(key)는 IAttendanceStatsStudentSummary 배열, pagination은 IPage.IPagination
 * 참조(현재페이지, 개수, 전체카운트, 전체페이지).
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIAttendanceStatsStudentSummary = {
  pagination?: IPage.IPagination;

  /** 학생별 기간요약 통계 배열. */
  data?: IAttendanceStatsStudentSummary[];
};
