import { IPage } from "./IPage";
import { IAttendanceAttendanceCode } from "./IAttendanceAttendanceCode";

/**
 * 출석코드 리스트 응답 페이징 컨테이너.
 *
 * 페이지네이션 정보와 출석코드 목록 배열을 포함하여 대시보드 리스트, 검색결과, UI바인딩 등에 직접 사용됩니다.
 *
 * Pagination은 공통 타입(IPage.IPagination) 참고.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageAttendanceAttendanceCode = {
  /** 페이지네이션 정보 */
  pagination: IPage.IPagination;

  /** 출석코드 개별 데이터 배열 */
  data: IAttendanceAttendanceCode[];
};
