import { IPage } from "./IPage";
import { IDiscussionBoardCommentVersion } from "./IDiscussionBoardCommentVersion";

/**
 * Paginated page of comment version records, used to deliver edit histories for
 * a comment to the client/auditor.
 *
 * Wraps pages of IDiscussionBoardCommentVersion (full or summary as needed),
 * together with pagination metadata for large comment histories. Used in
 * endpoints for comment version listing/browsing.
 *
 * Properties:
 *
 * - Pagination: IPage.IPagination; metadata for paging
 * - Data: array of comment version summary objects (see
 *   IDiscussionBoardCommentVersion or ISummary variant)
 *
 * Critical for moderation/audit flows where view or review of extended edit
 * history is needed, and for compliance presentation to end-users (e.g.,
 * 'edited 7 times - click for edit trail').
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIDiscussionBoardCommentVersion = {
  pagination: IPage.IPagination;

  /** Comment version objects for the current page. */
  data: IDiscussionBoardCommentVersion[];
};
