import { IPage } from "./IPage";
import { ISiteSetting } from "./ISiteSetting";

/**
 * Paginated response for site settings queries. Follows standard IPage<T>
 * pattern, providing metadata for pagination UI as well as the current slice of
 * site setting records for admin, audit, or compliance review.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageISiteSetting = {
  pagination: IPage.IPagination;

  /**
   * Array of site setting record(s) in the current page of results.
   *
   * Each entry represents a version or current configuration for the
   * discussion board.
   */
  data: ISiteSetting[];
};
