import { IPage } from "./IPage";
import { IDiscussionBoardThreadTag } from "./IDiscussionBoardThreadTag";

/**
 * 태그 검색/목록 페이징 결과 컨테이너.
 *
 * Pagination(페이지 정보)와 data(실제 태그 객체 배열)를 함께 제공합니다. 대량 데이터 처리시 UI 및 API 연결에
 * 최적화되어 있습니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIDiscussionBoardThreadTag = {
  pagination: IPage.IPagination;

  /** 해당 페이지에 있는 태그 레코드 객체 배열입니다. */
  data: IDiscussionBoardThreadTag[];
};
