import { tags } from "typia";

import { IPostEdit } from "./IPostEdit";
import { IPostVote } from "./IPostVote";
import { IComment } from "./IComment";

/**
 * 게시글(Post) 전체 엔터티 타입입니다.
 *
 * Prisma posts 테이블의 Atomic 컬럼 및 참조된 편집(EIDTS), 투표(VOTES), 코멘트(COMMENTS) 등 관계적
 * 데이터까지 포함한 객체입니다. 게시판 전체 동작, 상세 조회와 관리/감사에 적합한 구조입니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPost = {
  /**
   * 게시글 고유 ID.
   *
   * Prisma posts.id 컬럼을 사용합니다.
   */
  id: string & tags.Format<"uuid">;

  /**
   * 연결된 스레드의 ID.
   *
   * Prisma posts.thread_id 컬럼입니다.
   */
  thread_id: string & tags.Format<"uuid">;

  /**
   * 작성자(사용자) ID.
   *
   * Prisma posts.creator_id 컬럼.
   */
  creator_id: string & tags.Format<"uuid">;

  /**
   * 게시글 숨김 여부(관리자/모더레이터).
   *
   * Prisma posts.hidden 컬럼 활용. 표준 사용자에게는 숨겨질 수 있습니다.
   */
  hidden: boolean;

  /**
   * 게시글 최초 생성 시각.
   *
   * Prisma posts.created_at 컬럼.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * 게시글 최종 수정 시각.
   *
   * Prisma posts.updated_at 컬럼.
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * 소프트 삭제 시각(null이면 활성 상태).
   *
   * Prisma posts.deleted_at 컬럼.
   */
  deleted_at?: (string & tags.Format<"date-time">) | null;

  /**
   * 이 포스트의 편집(수정) 이력 목록.
   *
   * Post_edits 테이블과의 관계 기반.
   */
  edits?: IPostEdit[];

  /**
   * 이 포스트의 투표(업/다운) 이력.
   *
   * Post_votes 테이블 연결 결과.
   */
  votes?: IPostVote[];

  /** 이 포스트에 딸린 코멘트 요약 리스트. */
  comments?: IComment.ISummary[];
};
export namespace IPost {
  /**
   * 포스트(게시글) 검색·페이징·필터 요청용 타입입니다. threadsPosts.posts 테이블과 검색 UI에 맞춘 필수/선택 필터,
   * 정렬, 페이징 속성을 모두 포함합니다.
   */
  export type IRequest = {
    /** 페이지 번호. */
    page?:
      | (number &
          tags.Type<"int32"> &
          tags.JsonSchemaPlugin<{
            format: "uint32";
          }>)
      | null;

    /** 페이지 당 최대 항목 수. */
    limit?:
      | (number &
          tags.Type<"int32"> &
          tags.JsonSchemaPlugin<{
            format: "uint32";
          }>)
      | null;

    /** 키워드 검색용 질의 문자열입니다. 본문/편집 제목/작성자/기타 확장키워드 등에서 검색 활용. */
    search?: string | null;

    /** 특정 스레드 내에서만 게시글을 필터링할 경우 사용하는 thread ID입니다. */
    thread_id?: (string & tags.Format<"uuid">) | null;

    /** 특정 작성자(creator_id)별 게시글을 필터링할 때 사용. */
    creator_id?: (string & tags.Format<"uuid">) | null;

    /** 정렬 기준 필드(생성일/업데이트일 등). */
    order_by?: "created_at" | "updated_at";

    /** 내림차순 정렬 여부. */
    desc?: boolean;
  };

  /**
   * 게시글(포스트) 신규 등록용 바디 타입입니다.
   *
   * 본문(body)은 필수, thread_id(어느 스레드에 쓸지)는 필수입니다.
   */
  export type ICreate = {
    /**
     * 게시글이 속할 스레드 ID.
     *
     * Prisma posts.thread_id 컬럼 참조.
     */
    thread_id: string & tags.Format<"uuid">;

    /**
     * 글의 본문 내용.
     *
     * 포스트 생성 시 필수값.
     */
    body: string;
  };

  /**
   * 게시글(포스트) 수정 요청 타입입니다.
   *
   * 본문(body) 수정과, 숨김(hidden) 상태를 관리자가 조정할 수 있습니다.
   */
  export type IUpdate = {
    /**
     * 수정할 포스트 본문 내용.
     *
     * Prisma posts 본문 수정에 대응합니다.
     */
    body?: string | null;

    /** 게시글 숨김(관리목적) 여부를 변경합니다. */
    hidden?: boolean | null;
  };

  /** 포스트(게시글) 요약 타입. 목록 화면 등 기본 정보만 노출할 때 활용. */
  export type ISummary = {
    /**
     * 게시글 고유 ID (요약용).
     *
     * Prisma posts.id 컬럼 기반.
     */
    id: string & tags.Format<"uuid">;

    /**
     * 스레드 ID 요약.
     *
     * Prisma posts.thread_id 컬럼.
     */
    thread_id: string & tags.Format<"uuid">;

    /** 작성자(사용자) ID 요약. */
    creator_id: string & tags.Format<"uuid">;

    /** 게시글 최초 생성 시각. */
    created_at: string & tags.Format<"date-time">;

    /** 게시글 숨김 플래그(요약). */
    hidden: boolean;
  };
}
