import { tags } from "typia";

import { IPost } from "./IPost";
import { ITag } from "./ITag";

/**
 * 스레드(토론 주제) 엔터티 전체 스키마 타입입니다.
 *
 * 이 타입은 Prisma의 threads 테이블과 ERD의 모든 필드를 망라합니다. 각 토론은 하나의 카테고리에 속하고, 여러 태그 또는
 * 포스트와 관계를 가집니다. 게시판 비즈니스와 토론장 UI 및 검색/필터/정렬 등에 최적화된 구조입니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IThread = {
  /**
   * 스레드의 고유 식별자(ID).
   *
   * Prisma threads.id 컬럼 기반입니다. 각 토픽/스레드는 유일한 UUID를 가집니다.
   */
  id: string & tags.Format<"uuid">;

  /**
   * 스레드 생성자의 사용자 ID.
   *
   * Prisma threads.creator_id 컬럼에서 유래되었습니다.
   */
  creator_id: string & tags.Format<"uuid">;

  /**
   * 스레드가 속한 카테고리 ID입니다.
   *
   * Prisma threads.category_id 컬럼 기반.
   */
  category_id: string & tags.Format<"uuid">;

  /**
   * 스레드 제목(주제).
   *
   * Prisma threads.title 컬럼에서 유래되었습니다. UI에서 노출되는 핵심 텍스트입니다.
   */
  title: string;

  /**
   * 스레드 잠금 여부.
   *
   * Prisma threads.locked 컬럼에서 유래. 잠금 시 신규 게시물 작성이 제한됩니다.
   */
  locked: boolean;

  /**
   * 스레드 상단 고정 여부.
   *
   * Prisma threads.pinned 컬럼에서 유래. 중요 토픽/공지 등으로 상단 고정 시 true.
   */
  pinned: boolean;

  /**
   * 스레드 생성 시각.
   *
   * Prisma threads.created_at 컬럼에서 유래. 최신순 정렬 등에 사용.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * 스레드 최종 수정 시각.
   *
   * Prisma threads.updated_at 컬럼에서 유래.
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * 소프트 삭제(숨김) 시각.
   *
   * Prisma threads.deleted_at 컬럼에서 유래. null이면 활성, 값이 있으면 삭제 처리된 상태.
   */
  deleted_at?: (string & tags.Format<"date-time">) | null;

  /** 이 스레드에 속한 게시글(포스트) 요약 목록. */
  posts?: IPost.ISummary[];

  /** 스레드에 연결된 태그 목록. */
  tags?: ITag[];
};
export namespace IThread {
  /**
   * 스레드 검색, 필터, 페이징 요청용 타입입니다. 게시판의 스레드 목록을 조회할 때 사용합니다.
   *
   * Prisma threads 엔티티의 컬럼과 비즈니스 요구에 맞춰 설정된 필터/정렬/페이지 속성을 포함합니다.
   */
  export type IRequest = {
    /**
     * 페이지 번호(선택값).
     *
     * 기본값은 1입니다. 페이징 기반 요청 시 사용합니다.
     */
    page?:
      | (number &
          tags.Type<"int32"> &
          tags.JsonSchemaPlugin<{
            format: "uint32";
          }>)
      | null;

    /**
     * 페이지 당 최대 항목 수(선택값, 기본 100).
     *
     * 페이징, 페이지 사이즈 조절 등에 활용됩니다.
     */
    limit?:
      | (number &
          tags.Type<"int32"> &
          tags.JsonSchemaPlugin<{
            format: "uint32";
          }>)
      | null;

    /**
     * 키워드 검색어.
     *
     * 스레드 제목이나 내용, 태그 등에 대한 검색 쿼리입니다.
     */
    search?: string | null;

    /**
     * 카테고리 필터링용 ID.
     *
     * 특정 카테고리 내 스레드만 필터링할 때 사용합니다.
     */
    category_id?: (string & tags.Format<"uuid">) | null;

    /**
     * 태그에 해당되는 스레드만 필터링합니다.
     *
     * 스레드-태그 관계에서 태그 기준으로 추출할 때 활용합니다.
     */
    tag_id?: (string & tags.Format<"uuid">) | null;

    /** 정렬 기준 필드 (생성일자, 수정일자, 제목 등). */
    order_by?: "created_at" | "updated_at" | "title";

    /** 내림차순 정렬 여부. true면 내림차순, false면 오름차순입니다. */
    desc?: boolean;
  };

  /**
   * 신규 스레드 생성용 요청 바디 타입입니다.
   *
   * 카테고리, 제목, 태그 지정이 가능하며, threads 테이블의 not-null 필드 요구사항과 비즈니스 로직을 반영합니다. 생성
   * 후 추가 관계(포스트 작성, 태그 바인딩 등) 진행 가능합니다.
   */
  export type ICreate = {
    /**
     * 신규 스레드를 속할 카테고리 ID.
     *
     * Prisma threads.category_id 컬럼 참조. 필수.
     */
    category_id: string & tags.Format<"uuid">;

    /**
     * 스레드(토론)의 제목, 필수.
     *
     * Prisma threads.title 컬럼 기반. 제목은 카테고리 내에서 유일해야 하며, UI에서 노출되는 핵심
     * 텍스트입니다.
     */
    title: string;

    /**
     * 초기 등록할 태그 ID 리스트.
     *
     * 스레드-태그 관계를 미리 세팅할 때 활용합니다. (Prisma thread_tags)
     */
    tags?: (string & tags.Format<"uuid">)[];
  };

  /**
   * 스레드(threads) 정보 갱신용 타입. 전체 필드 중 일부만 선택적으로 변경 가능하며, 카테고리/제목/상태/태그를 특정 유저의
   * 권한에 따라 조정할 때 활용합니다.
   */
  export type IUpdate = {
    /**
     * 수정할 카테고리 ID (선택).
     *
     * Prisma threads.category_id 컬럼 기반. 스레드 이동시 사용.
     */
    category_id?: (string & tags.Format<"uuid">) | null;

    /**
     * 스레드 제목 수정 값.
     *
     * Prisma threads.title 컬럼 기반. 제목 변경시 사용.
     */
    title?: string | null;

    /**
     * 잠금 여부(선택값).
     *
     * Moderator/Admin이 토론 제한/허용 시 활용.
     */
    locked?: boolean | null;

    /**
     * 상단 고정 여부(선택값).
     *
     * Moderator가 중요 토픽 알리고자 할 때 사용.
     */
    pinned?: boolean | null;

    /**
     * 스레드에 추가(또는 제거)할 태그 ID 목록.
     *
     * 태그 관리 또는 토론 분류 변경 시 활용.
     */
    tags?: (string & tags.Format<"uuid">)[] | null;
  };

  /** 스레드(토론) 요약 타입입니다. 목록 API 응답에 포함되는 필수 정보만 추려 구성합니다. */
  export type ISummary = {
    /**
     * 스레드의 고유 식별자(ID) - 요약형.
     *
     * Prisma threads.id 컬럼 기반. 짧은 리스트 뷰 등에 쓰입니다.
     */
    id: string & tags.Format<"uuid">;

    /**
     * 스레드 제목 요약.
     *
     * Prisma threads.title 컬럼 요약값.
     */
    title: string;

    /** 생성자 사용자 ID. */
    creator_id: string & tags.Format<"uuid">;

    /** 스레드 카테고리 ID. */
    category_id: string & tags.Format<"uuid">;

    /**
     * 잠금상태 플래그 요약.
     *
     * Prisma threads.locked 컬럼 간략조회용.
     */
    locked: boolean;

    /** 상단 고정 플래그 요약. */
    pinned: boolean;

    /** 스레드 생성 시각. */
    created_at: string & tags.Format<"date-time">;
  };
}
